"""Canonical wire/database vocabulary for veldt-kya.

Every value here appears on the wire (HTTP body, DB column, config file).
Renaming a value is a wire-breaking change. Callers use the named
constants; ``CANONICAL_*`` frozensets/tuples are the whitelists.
"""
from __future__ import annotations


# ── Verdicts ────────────────────────────────────────────────────────

VERDICT_ALLOW: str = "allow"
VERDICT_DENY: str = "deny"
VERDICT_FLAG_FOR_REVIEW: str = "flag_for_review"
VERDICT_BLOCK: str = "block"
VERDICT_REDACT: str = "redact"
VERDICT_THROTTLE: str = "throttle"
VERDICT_ANONYMIZE: str = "anonymize"

# Pro-visible extensions — not part of the 7-core canonical set.
VERDICT_ESCALATE: str = "escalate"
VERDICT_ALERT: str = "alert"

CANONICAL_VERDICTS: frozenset[str] = frozenset({
    VERDICT_ALLOW,
    VERDICT_DENY,
    VERDICT_FLAG_FOR_REVIEW,
    VERDICT_BLOCK,
    VERDICT_REDACT,
    VERDICT_THROTTLE,
    VERDICT_ANONYMIZE,
})


# ── Outcomes ────────────────────────────────────────────────────────

OUTCOME_SUCCESS: str = "success"
OUTCOME_FAILURE: str = "failure"
OUTCOME_REFUSED: str = "refused"
OUTCOME_DENIED: str = "denied"
OUTCOME_BLOCKED: str = "blocked"
OUTCOME_ERROR: str = "error"
OUTCOME_THROTTLED: str = "throttled"
OUTCOME_PARTIAL: str = "partial"
OUTCOME_IN_PROGRESS: str = "in_progress"
OUTCOME_PENDING: str = "pending"

CANONICAL_OUTCOMES: frozenset[str] = frozenset({
    OUTCOME_SUCCESS,
    OUTCOME_FAILURE,
    OUTCOME_REFUSED,
    OUTCOME_DENIED,
    OUTCOME_BLOCKED,
    OUTCOME_ERROR,
    OUTCOME_THROTTLED,
    OUTCOME_PARTIAL,
    OUTCOME_IN_PROGRESS,
    OUTCOME_PENDING,
})


# ── Evidence kinds ──────────────────────────────────────────────────

EVIDENCE_KIND_PROMPT: str = "prompt"
EVIDENCE_KIND_RESPONSE: str = "response"
EVIDENCE_KIND_TOOL_CALL: str = "tool_call"
EVIDENCE_KIND_TOOL_RESULT: str = "tool_result"
EVIDENCE_KIND_DELEGATION_MESSAGE: str = "delegation_message"
EVIDENCE_KIND_HIL_DECISION: str = "hil_decision"
EVIDENCE_KIND_SYSTEM_MESSAGE: str = "system_message"
EVIDENCE_KIND_JUDGE_VERDICT: str = "judge_verdict"

EVIDENCE_KIND_RUNTIME_FALCO: str = "runtime_falco"
EVIDENCE_KIND_RUNTIME_TETRAGON: str = "runtime_tetragon"
EVIDENCE_KIND_RUNTIME_TRACEE: str = "runtime_tracee"
EVIDENCE_KIND_RUNTIME_SYSDIG: str = "runtime_sysdig"
EVIDENCE_KIND_RUNTIME_OSQUERY: str = "runtime_osquery"
EVIDENCE_KIND_RUNTIME_AUDITD: str = "runtime_auditd"
EVIDENCE_KIND_RUNTIME_K8S_AUDIT: str = "runtime_k8s_audit"
EVIDENCE_KIND_RUNTIME_EBPF: str = "runtime_ebpf"

EVIDENCE_KIND_AUTONOMY_MAVLINK: str = "autonomy_mavlink"

EVIDENCE_KIND_ISSUER_VC_ISSUED: str = "issuer_vc_issued"
EVIDENCE_KIND_ISSUER_VC_REVOKED: str = "issuer_vc_revoked"
EVIDENCE_KIND_ISSUER_VC_REVOKE_ALREADY_SET: str = "issuer_vc_revoke_already_set"
EVIDENCE_KIND_TRUST_REGISTRY_CHANGE: str = "trust_registry_change"
EVIDENCE_KIND_GATEWAY_VERDICT: str = "gateway_verdict"
EVIDENCE_KIND_REVOCATION_BLOCKED: str = "revocation_blocked"
EVIDENCE_KIND_DPOP_REPLAY: str = "dpop_replay"
EVIDENCE_KIND_DPOP_FORGE_ATTEMPT: str = "dpop_forge_attempt"
EVIDENCE_KIND_DPOP_EXPIRED: str = "dpop_expired"
EVIDENCE_KIND_ISSUER_ROTATION_PENDING: str = "issuer_rotation_pending"

EVIDENCE_KIND_VC_REQUEST_QUEUED: str = "vc_request_queued"
EVIDENCE_KIND_VC_REQUEST_APPROVED: str = "vc_request_approved"
EVIDENCE_KIND_VC_REQUEST_AUTO_APPROVED: str = "vc_request_auto_approved"
EVIDENCE_KIND_VC_REQUEST_DENIED: str = "vc_request_denied"

EVIDENCE_KIND_ACTION_GATE_BLOCK: str = "action_gate_block"
EVIDENCE_KIND_EXTERNAL_ALERT: str = "external_alert"

# ABAC-reserved evidence kinds — reserved here so future ABAC chunks
# don't touch this module.
EVIDENCE_KIND_ABAC_DECISION: str = "abac_decision"
EVIDENCE_KIND_ABAC_SHADOW_EVAL: str = "abac_shadow_eval"
EVIDENCE_KIND_ABAC_NATIVE_OVERRIDE: str = "abac_native_override"

CANONICAL_EVIDENCE_KINDS: frozenset[str] = frozenset({
    EVIDENCE_KIND_PROMPT,
    EVIDENCE_KIND_RESPONSE,
    EVIDENCE_KIND_TOOL_CALL,
    EVIDENCE_KIND_TOOL_RESULT,
    EVIDENCE_KIND_DELEGATION_MESSAGE,
    EVIDENCE_KIND_HIL_DECISION,
    EVIDENCE_KIND_SYSTEM_MESSAGE,
    EVIDENCE_KIND_JUDGE_VERDICT,
    EVIDENCE_KIND_RUNTIME_FALCO,
    EVIDENCE_KIND_RUNTIME_TETRAGON,
    EVIDENCE_KIND_RUNTIME_TRACEE,
    EVIDENCE_KIND_RUNTIME_SYSDIG,
    EVIDENCE_KIND_RUNTIME_OSQUERY,
    EVIDENCE_KIND_RUNTIME_AUDITD,
    EVIDENCE_KIND_RUNTIME_K8S_AUDIT,
    EVIDENCE_KIND_RUNTIME_EBPF,
    EVIDENCE_KIND_AUTONOMY_MAVLINK,
    EVIDENCE_KIND_ISSUER_VC_ISSUED,
    EVIDENCE_KIND_ISSUER_VC_REVOKED,
    EVIDENCE_KIND_ISSUER_VC_REVOKE_ALREADY_SET,
    EVIDENCE_KIND_TRUST_REGISTRY_CHANGE,
    EVIDENCE_KIND_GATEWAY_VERDICT,
    EVIDENCE_KIND_REVOCATION_BLOCKED,
    EVIDENCE_KIND_DPOP_REPLAY,
    EVIDENCE_KIND_DPOP_FORGE_ATTEMPT,
    EVIDENCE_KIND_DPOP_EXPIRED,
    EVIDENCE_KIND_ISSUER_ROTATION_PENDING,
    EVIDENCE_KIND_VC_REQUEST_QUEUED,
    EVIDENCE_KIND_VC_REQUEST_APPROVED,
    EVIDENCE_KIND_VC_REQUEST_AUTO_APPROVED,
    EVIDENCE_KIND_VC_REQUEST_DENIED,
    EVIDENCE_KIND_ACTION_GATE_BLOCK,
    EVIDENCE_KIND_EXTERNAL_ALERT,
    EVIDENCE_KIND_ABAC_DECISION,
    EVIDENCE_KIND_ABAC_SHADOW_EVAL,
    EVIDENCE_KIND_ABAC_NATIVE_OVERRIDE,
})


# ── Principal kinds ─────────────────────────────────────────────────

PRINCIPAL_KIND_USER: str = "user"
PRINCIPAL_KIND_AGENT: str = "agent"
PRINCIPAL_KIND_SERVICE_ACCOUNT: str = "service_account"
PRINCIPAL_KIND_ADMIN: str = "admin"

PRINCIPAL_KIND_DRONE: str = "drone"
PRINCIPAL_KIND_ROBOT: str = "robot"
PRINCIPAL_KIND_VEHICLE: str = "vehicle"
PRINCIPAL_KIND_PLC: str = "plc"
PRINCIPAL_KIND_SCADA: str = "scada"
PRINCIPAL_KIND_CONTROLLER: str = "controller"
PRINCIPAL_KIND_SENSOR: str = "sensor"
PRINCIPAL_KIND_ACTUATOR: str = "actuator"
PRINCIPAL_KIND_LAKEHOUSE_JOB: str = "lakehouse_job"
PRINCIPAL_KIND_MACHINE_IDENTITY: str = "machine_identity"
PRINCIPAL_KIND_AUTONOMOUS_SYSTEM: str = "autonomous_system"

# Tuple preserves insertion order — matches ``kya.principals.PRINCIPAL_KINDS``.
CANONICAL_PRINCIPAL_KINDS: tuple[str, ...] = (
    PRINCIPAL_KIND_USER,
    PRINCIPAL_KIND_AGENT,
    PRINCIPAL_KIND_SERVICE_ACCOUNT,
    PRINCIPAL_KIND_DRONE,
    PRINCIPAL_KIND_ROBOT,
    PRINCIPAL_KIND_VEHICLE,
    PRINCIPAL_KIND_PLC,
    PRINCIPAL_KIND_SCADA,
    PRINCIPAL_KIND_CONTROLLER,
    PRINCIPAL_KIND_SENSOR,
    PRINCIPAL_KIND_ACTUATOR,
    PRINCIPAL_KIND_LAKEHOUSE_JOB,
    PRINCIPAL_KIND_MACHINE_IDENTITY,
    PRINCIPAL_KIND_AUTONOMOUS_SYSTEM,
    PRINCIPAL_KIND_ADMIN,
)


# ── Signal kinds ────────────────────────────────────────────────────

SIGNAL_KIND_OOS_TOOL: str = "oos_tool"
SIGNAL_KIND_CROSS_TENANT: str = "cross_tenant"
SIGNAL_KIND_DATA_LEAK: str = "data_leak"
SIGNAL_KIND_RBAC_REFUSAL: str = "rbac_refusal"
SIGNAL_KIND_GOVERNANCE_BLOCK: str = "governance_block"
SIGNAL_KIND_HALLUCINATION: str = "hallucination"
SIGNAL_KIND_INJECTION_ATTEMPT: str = "injection_attempt"
SIGNAL_KIND_DEFINITION_DRIFT: str = "definition_drift"
SIGNAL_KIND_POLICY_VIOLATION: str = "policy_violation"
SIGNAL_KIND_AGENT_FIRST_SIGHT: str = "agent_first_sight"
SIGNAL_KIND_RATE_LIMIT_EXCEEDED: str = "rate_limit_exceeded"
SIGNAL_KIND_PAYLOAD_TOO_LARGE: str = "payload_too_large"
SIGNAL_KIND_REPLAY_DETECTED: str = "replay_detected"
SIGNAL_KIND_REVOCATION_BLOCKED: str = "revocation_blocked"
SIGNAL_KIND_DPOP_REPLAY: str = "dpop_replay"
SIGNAL_KIND_DPOP_FORGE_ATTEMPT: str = "dpop_forge_attempt"
SIGNAL_KIND_DPOP_EXPIRED: str = "dpop_expired"
SIGNAL_KIND_ISSUER_ROTATION_PENDING: str = "issuer_rotation_pending"
SIGNAL_KIND_VC_APPROVAL_DENIED: str = "vc_approval_denied"
SIGNAL_KIND_BUDGET_EXCEEDED: str = "budget_exceeded"
SIGNAL_KIND_BUDGET_ERROR: str = "budget_error"

CANONICAL_SIGNAL_KINDS: frozenset[str] = frozenset({
    SIGNAL_KIND_OOS_TOOL,
    SIGNAL_KIND_CROSS_TENANT,
    SIGNAL_KIND_DATA_LEAK,
    SIGNAL_KIND_RBAC_REFUSAL,
    SIGNAL_KIND_GOVERNANCE_BLOCK,
    SIGNAL_KIND_HALLUCINATION,
    SIGNAL_KIND_INJECTION_ATTEMPT,
    SIGNAL_KIND_DEFINITION_DRIFT,
    SIGNAL_KIND_POLICY_VIOLATION,
    SIGNAL_KIND_AGENT_FIRST_SIGHT,
    SIGNAL_KIND_RATE_LIMIT_EXCEEDED,
    SIGNAL_KIND_PAYLOAD_TOO_LARGE,
    SIGNAL_KIND_REPLAY_DETECTED,
    SIGNAL_KIND_REVOCATION_BLOCKED,
    SIGNAL_KIND_DPOP_REPLAY,
    SIGNAL_KIND_DPOP_FORGE_ATTEMPT,
    SIGNAL_KIND_DPOP_EXPIRED,
    SIGNAL_KIND_ISSUER_ROTATION_PENDING,
    SIGNAL_KIND_VC_APPROVAL_DENIED,
    SIGNAL_KIND_BUDGET_EXCEEDED,
    SIGNAL_KIND_BUDGET_ERROR,
})


# ── ABAC lifecycle states (reserved) ────────────────────────────────

LIFECYCLE_STATE_DRAFT: str = "draft"
LIFECYCLE_STATE_STAGED: str = "staged"
LIFECYCLE_STATE_ACTIVE: str = "active"
LIFECYCLE_STATE_DEPRECATED: str = "deprecated"
LIFECYCLE_STATE_ARCHIVED: str = "archived"

CANONICAL_LIFECYCLE_STATES: frozenset[str] = frozenset({
    LIFECYCLE_STATE_DRAFT,
    LIFECYCLE_STATE_STAGED,
    LIFECYCLE_STATE_ACTIVE,
    LIFECYCLE_STATE_DEPRECATED,
    LIFECYCLE_STATE_ARCHIVED,
})


# ── ABAC composition modes (reserved) ───────────────────────────────

COMPOSITION_MODE_ABAC_ONLY: str = "abac_only"
COMPOSITION_MODE_ABAC_THEN_NATIVE: str = "abac_then_native"
COMPOSITION_MODE_NATIVE_THEN_ABAC: str = "native_then_abac"
COMPOSITION_MODE_ABAC_AUGMENTS_NATIVE: str = "abac_augments_native"

CANONICAL_COMPOSITION_MODES: frozenset[str] = frozenset({
    COMPOSITION_MODE_ABAC_ONLY,
    COMPOSITION_MODE_ABAC_THEN_NATIVE,
    COMPOSITION_MODE_NATIVE_THEN_ABAC,
    COMPOSITION_MODE_ABAC_AUGMENTS_NATIVE,
})

# ``abac_veto_native`` is intentionally excluded — an ABAC veto over a
# native allow inverts the fail-closed contract. Fail fast at import.
assert "abac_veto_native" not in CANONICAL_COMPOSITION_MODES


__all__ = [
    # Verdicts
    "VERDICT_ALLOW",
    "VERDICT_DENY",
    "VERDICT_FLAG_FOR_REVIEW",
    "VERDICT_BLOCK",
    "VERDICT_REDACT",
    "VERDICT_THROTTLE",
    "VERDICT_ANONYMIZE",
    "VERDICT_ESCALATE",
    "VERDICT_ALERT",
    "CANONICAL_VERDICTS",
    # Outcomes
    "OUTCOME_SUCCESS",
    "OUTCOME_FAILURE",
    "OUTCOME_REFUSED",
    "OUTCOME_DENIED",
    "OUTCOME_BLOCKED",
    "OUTCOME_ERROR",
    "OUTCOME_THROTTLED",
    "OUTCOME_PARTIAL",
    "OUTCOME_IN_PROGRESS",
    "OUTCOME_PENDING",
    "CANONICAL_OUTCOMES",
    # Evidence kinds
    "EVIDENCE_KIND_PROMPT",
    "EVIDENCE_KIND_RESPONSE",
    "EVIDENCE_KIND_TOOL_CALL",
    "EVIDENCE_KIND_TOOL_RESULT",
    "EVIDENCE_KIND_DELEGATION_MESSAGE",
    "EVIDENCE_KIND_HIL_DECISION",
    "EVIDENCE_KIND_SYSTEM_MESSAGE",
    "EVIDENCE_KIND_JUDGE_VERDICT",
    "EVIDENCE_KIND_RUNTIME_FALCO",
    "EVIDENCE_KIND_RUNTIME_TETRAGON",
    "EVIDENCE_KIND_RUNTIME_TRACEE",
    "EVIDENCE_KIND_RUNTIME_SYSDIG",
    "EVIDENCE_KIND_RUNTIME_OSQUERY",
    "EVIDENCE_KIND_RUNTIME_AUDITD",
    "EVIDENCE_KIND_RUNTIME_K8S_AUDIT",
    "EVIDENCE_KIND_RUNTIME_EBPF",
    "EVIDENCE_KIND_AUTONOMY_MAVLINK",
    "EVIDENCE_KIND_ISSUER_VC_ISSUED",
    "EVIDENCE_KIND_ISSUER_VC_REVOKED",
    "EVIDENCE_KIND_ISSUER_VC_REVOKE_ALREADY_SET",
    "EVIDENCE_KIND_TRUST_REGISTRY_CHANGE",
    "EVIDENCE_KIND_GATEWAY_VERDICT",
    "EVIDENCE_KIND_REVOCATION_BLOCKED",
    "EVIDENCE_KIND_DPOP_REPLAY",
    "EVIDENCE_KIND_DPOP_FORGE_ATTEMPT",
    "EVIDENCE_KIND_DPOP_EXPIRED",
    "EVIDENCE_KIND_ISSUER_ROTATION_PENDING",
    "EVIDENCE_KIND_VC_REQUEST_QUEUED",
    "EVIDENCE_KIND_VC_REQUEST_APPROVED",
    "EVIDENCE_KIND_VC_REQUEST_AUTO_APPROVED",
    "EVIDENCE_KIND_VC_REQUEST_DENIED",
    "EVIDENCE_KIND_ACTION_GATE_BLOCK",
    "EVIDENCE_KIND_EXTERNAL_ALERT",
    "EVIDENCE_KIND_ABAC_DECISION",
    "EVIDENCE_KIND_ABAC_SHADOW_EVAL",
    "EVIDENCE_KIND_ABAC_NATIVE_OVERRIDE",
    "CANONICAL_EVIDENCE_KINDS",
    # Principal kinds
    "PRINCIPAL_KIND_USER",
    "PRINCIPAL_KIND_AGENT",
    "PRINCIPAL_KIND_SERVICE_ACCOUNT",
    "PRINCIPAL_KIND_ADMIN",
    "PRINCIPAL_KIND_DRONE",
    "PRINCIPAL_KIND_ROBOT",
    "PRINCIPAL_KIND_VEHICLE",
    "PRINCIPAL_KIND_PLC",
    "PRINCIPAL_KIND_SCADA",
    "PRINCIPAL_KIND_CONTROLLER",
    "PRINCIPAL_KIND_SENSOR",
    "PRINCIPAL_KIND_ACTUATOR",
    "PRINCIPAL_KIND_LAKEHOUSE_JOB",
    "PRINCIPAL_KIND_MACHINE_IDENTITY",
    "PRINCIPAL_KIND_AUTONOMOUS_SYSTEM",
    "CANONICAL_PRINCIPAL_KINDS",
    # Signal kinds
    "SIGNAL_KIND_OOS_TOOL",
    "SIGNAL_KIND_CROSS_TENANT",
    "SIGNAL_KIND_DATA_LEAK",
    "SIGNAL_KIND_RBAC_REFUSAL",
    "SIGNAL_KIND_GOVERNANCE_BLOCK",
    "SIGNAL_KIND_HALLUCINATION",
    "SIGNAL_KIND_INJECTION_ATTEMPT",
    "SIGNAL_KIND_DEFINITION_DRIFT",
    "SIGNAL_KIND_POLICY_VIOLATION",
    "SIGNAL_KIND_AGENT_FIRST_SIGHT",
    "SIGNAL_KIND_RATE_LIMIT_EXCEEDED",
    "SIGNAL_KIND_PAYLOAD_TOO_LARGE",
    "SIGNAL_KIND_REPLAY_DETECTED",
    "SIGNAL_KIND_REVOCATION_BLOCKED",
    "SIGNAL_KIND_DPOP_REPLAY",
    "SIGNAL_KIND_DPOP_FORGE_ATTEMPT",
    "SIGNAL_KIND_DPOP_EXPIRED",
    "SIGNAL_KIND_ISSUER_ROTATION_PENDING",
    "SIGNAL_KIND_VC_APPROVAL_DENIED",
    "SIGNAL_KIND_BUDGET_EXCEEDED",
    "SIGNAL_KIND_BUDGET_ERROR",
    "CANONICAL_SIGNAL_KINDS",
    # Lifecycle states
    "LIFECYCLE_STATE_DRAFT",
    "LIFECYCLE_STATE_STAGED",
    "LIFECYCLE_STATE_ACTIVE",
    "LIFECYCLE_STATE_DEPRECATED",
    "LIFECYCLE_STATE_ARCHIVED",
    "CANONICAL_LIFECYCLE_STATES",
    # Composition modes
    "COMPOSITION_MODE_ABAC_ONLY",
    "COMPOSITION_MODE_ABAC_THEN_NATIVE",
    "COMPOSITION_MODE_NATIVE_THEN_ABAC",
    "COMPOSITION_MODE_ABAC_AUGMENTS_NATIVE",
    "CANONICAL_COMPOSITION_MODES",
]
